---

- hosts: all
  become: true
  tasks:
  
  - name: update repository index
    apt:
      update_cache: yes 
    when: ansible_os_family == "Debian"
  
  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_os_family == "Debian"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
    when: ansible_os_family == "Debian"

  - name: update repository index
    yum:
      update_cache: yes 
    when: ansible_os_family == "Rocky"

  - name: install httpd package
    yum:
      name: httpd
      state: latest
    when: ansible_os_family == "Rocky"

  - name: add php support for httpd
    yum:
      name: php
    when: ansible_os_family == "Rocky"






